name: Create and publish release
on: [workflow_dispatch]
permissions:
  contents: write

env:
  node-version: 18

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn lint:all
      - run: yarn tsc
      - run: yarn build

  release-please:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: '@sammbetts/backstage-plugin-service-health'

  tagged-release:
    name: Create tagged release
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git pull
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
          files: 'CHANGELOG.md'

  frontend-publish:
    name: Publish plugin frontend
    runs-on: ubuntu-latest
    needs: tagged-release
    defaults:
      run:
        working-directory: ./plugins/service-health-dashboard
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create yarnrc.yml
        run: |
          echo "npmAuthToken: ${{ secrets.NPM_TOKEN }}" >> ~/.yarnrc.yml
          echo "npmAlwaysAuth: true" >> ~/.yarnrc.yml
          echo "npmPublishRegistry: https://registry.npmjs.org" >> ~/.yarnrc.yml
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - run: git pull
      - run: yarn
      - run: yarn tsc
      - run: yarn build
      - run: npm publish

  backend-publish:
    name: Publish plugin backend
    runs-on: ubuntu-latest
    needs: tagged-release
    defaults:
      run:
        working-directory: ./plugins/service-health-backend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create yarnrc.yml
        run: |
          echo "npmAuthToken: ${{ secrets.NPM_TOKEN }}" >> ~/.yarnrc.yml
          echo "npmAlwaysAuth: true" >> ~/.yarnrc.yml
          echo "npmPublishRegistry: https://registry.npmjs.org" >> ~/.yarnrc.yml
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - run: git pull
      - run: yarn
      - run: yarn tsc
      - run: yarn build
      - run: npm publish
